# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BD GH Action

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:
  build:

    runs-on: [ ubuntu-latest ]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    
    - name: Black Duck Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.8.0
      env:
        DETECT_PROJECT_NAME: RDJ_GHA_DuckHub
      with:
        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_full: true
        blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
        blackduck_reports_sarif_create: true
        blackduck_upload_sarif_report: true
        GITHUB_TOKEN: ${{ github.token }}
